In [3]:
import pandas as pd

In [4]:
df_consumption = pd.read_excel("DATASET_cultural dimension of food consumption.xlsx")

In [5]:
df_consumption.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 28 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   (A1) CITY                                                              710 non-null    object
 1   (A2) PROVINCE                                                          710 non-null    object
 2   (B3) GENDER                                                            710 non-null    object
 3   (B4) AGE                                                               710 non-null    int64
 4   (B5) RELIGION                                                          710 non-null    object
 5   (B6) ETHNIC                                                            710 non-null    object
 6   (B7) EDUCATION LEVEL                                                   710 non-null    object
 7   (B8) LIVED IN URBAN AREA (YEARS)                                       710 non-null    int64
 8   (B9) OCCUPATION                                                        710 non-null    object
 9   (B10) SOCIAL CLAS                                                      710 non-null    object
 10  (B11) HOUSEHOLD MEMBER                                                 710 non-null    int64
 11  (C12) HOUSEHOLD INCOME (MONTHLY IN MILLION IDR)                        710 non-null    object
 12  (C13) TIME OF INCOME RECEIPT                                           710 non-null    object
 13  (C14) HOUSEHOLD EXPENDITURE (MONTHLY IN MILLION IDR)                   710 non-null    object
 14  (C15) % MONTHLY EXPENDITURE FOR FOOD                                   710 non-null    int64
 15  (D16) HEALTH FACTOR                                                    710 non-null    object
 16  (D17) PRICE FACTOR)                                                    710 non-null    object
 17  (E18) RELIGIOUS VALUE IN TYPE OF FOOD                                  710 non-null    object
 18  (E19) RELIGIOUS VALUE IN EATING PLACES                                 710 non-null    object
 19  (E20) RELIGIOUS VALUE IN CONSUMPTION PATTERN                           710 non-null    object
 20  (E21) CUSTOM VALUE IN TYPE OF FOOD                                     710 non-null    object
 21  (E22) CUSTOM VALUE IN EATING PLACES                                    710 non-null    object
 22  (E23) CUSTOM VALUE IN CONSUMPTION PATTERN                              710 non-null    object
 23  (24) PRACTICE OF FOOD CONSUMPTION BASED ON RELIGIOUS RULES             710 non-null    object
 24  (25) PRACTICE OF FOOD CONSUMPTION BASED ON CUSTOM RULES                710 non-null    object
 25  (E26) BUYING FOOD PRODUCT IN THE RIGHT PLACE BASED ON RELIGIOUS RULES  710 non-null    object
 26  (E27 TYPE OF DISHES VARIATION BASED ON RELIGIOUS RULES                 710 non-null    object
 27  (E28) PRACTICE OF CONSUMING TRADITIONAL FOOD                           710 non-null    object
dtypes: int64(4), object(24)
memory usage: 155.4+ KB

In [6]:
len(df_consumption.drop_duplicates()) / len(df_consumption)
#jika output dari code di cell ini tidak bernilai 1 maka terdapat duplikat

1.0

## Data Cleaning Review

1. Tidak ada missing value ketika dicek dengan fungsi isna
2. Tidak ada duplikated data pada dataset ini

In [7]:
df_consumption.head()

,(A1) CITY,(A2) PROVINCE,(B3) GENDER,(B4) AGE,(B5) RELIGION,(B6) ETHNIC,(B7) EDUCATION LEVEL,(B8) LIVED IN URBAN AREA (YEARS),(B9) OCCUPATION,(B10) SOCIAL CLAS,...,(E19) RELIGIOUS VALUE IN EATING PLACES,(E20) RELIGIOUS VALUE IN CONSUMPTION PATTERN,(E21) CUSTOM VALUE IN TYPE OF FOOD,(E22) CUSTOM VALUE IN EATING PLACES,(E23) CUSTOM VALUE IN CONSUMPTION PATTERN,(24) PRACTICE OF FOOD CONSUMPTION BASED ON RELIGIOUS RULES,(25) PRACTICE OF FOOD CONSUMPTION BASED ON CUSTOM RULES,(E26) BUYING FOOD PRODUCT IN THE RIGHT PLACE BASED ON RELIGIOUS RULES,(E27 TYPE OF DISHES VARIATION BASED ON RELIGIOUS RULES,(E28) PRACTICE OF CONSUMING TRADITIONAL FOOD
0,Jakarta,DKI Jakarta,Female,31,Islam,Java,Senior High School,31,Private Employees,Lower Class,...,Neither agree nor disagree,Agree,Strongly Agree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Disagree,Neither agree nor disagree,Agree,Agree
1,Jakarta,DKI Jakarta,Female,36,Islam,Java,Bachelor degree,32,Private Employees,Lower Class,...,Agree,Agree,Strongly Agree,Agree,Agree,Disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Strongly Agree
2,Jakarta,DKI Jakarta,Male,24,Islam,Java,Senior High School,24,Private Employees,Middle Class,...,Agree,Neither agree nor disagree,Neither agree nor disagree,Disagree,Agree,Disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree
3,Jakarta,DKI Jakarta,Female,63,Islam,Other,Senior High School,32,Private Employees,Lower Class,...,Agree,Neither agree nor disagree,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,Disagree,Neither agree nor disagree,Agree
4,Jakarta,DKI Jakarta,Male,43,Protestant,Batak,Primary School,43,Government Employees,Lower Class,...,Strongly Agree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Strongly Agree,Strongly Agree,Agree,Disagree,Agree,Agree

In [8]:
# Misalnya, lihat distribusi nilai religius terhadap jenis makanan
df_consumption['(E18) RELIGIOUS VALUE IN TYPE OF FOOD'].value_counts()

(E18) RELIGIOUS VALUE IN TYPE OF FOOD
Strongly Agree                391
Agree                         194
Neither agree nor disagree    116
Disagree                        8
Strongly Disagree               1
Name: count, dtype: int64